export type UiRegistryItem = {
  name: string
  description: string
  status: 'implemented' | 'alias' | 'planned'
  localComponent?: string
}

export const uiRegistry: UiRegistryItem[] = [
  { name: 'Accordion', description: 'Раскрывающиеся секции контента.', status: 'implemented', localComponent: 'UiAccordion' },
  { name: 'Alert', description: 'Callout для важных сообщений.', status: 'implemented', localComponent: 'UiAlert' },
  { name: 'Alert Dialog', description: 'Критическое подтверждение действия.', status: 'alias', localComponent: 'UiDialog' },
  { name: 'Aspect Ratio', description: 'Контейнер с фиксированным соотношением сторон.', status: 'implemented', localComponent: 'UiAspectRatio' },
  { name: 'Avatar', description: 'Аватар пользователя с fallback.', status: 'implemented', localComponent: 'UiAvatar' },
  { name: 'Badge', description: 'Метки статусов и категорий.', status: 'implemented', localComponent: 'UiBadge' },
  { name: 'Breadcrumb', description: 'Иерархический путь страницы.', status: 'implemented', localComponent: 'UiBreadcrumb' },
  { name: 'Button', description: 'Кнопки с вариантами и размерами.', status: 'implemented', localComponent: 'AppButton' },
  { name: 'Button Group', description: 'Группа связанных кнопок.', status: 'implemented', localComponent: 'UiButtonGroup' },
  { name: 'Calendar', description: 'Легкий календарь для админки.', status: 'implemented', localComponent: 'UiCalendar' },
  { name: 'Card', description: 'Контейнер для блоков интерфейса.', status: 'implemented', localComponent: 'UiCard' },
  { name: 'Carousel', description: 'Переключение карточек/подсказок.', status: 'implemented', localComponent: 'UiCarousel' },
  { name: 'Chart', description: 'Простой bar-chart для отчетов.', status: 'implemented', localComponent: 'UiChart' },
  { name: 'Checkbox', description: 'Двоичный выбор.', status: 'implemented', localComponent: 'UiCheckbox' },
  { name: 'Collapsible', description: 'Свернуть/развернуть панель.', status: 'implemented', localComponent: 'UiCollapsible' },
  { name: 'Combobox', description: 'Поиск и выбор из списка.', status: 'alias', localComponent: 'UiCommand' },
  { name: 'Command', description: 'Командное меню и быстрый поиск.', status: 'implemented', localComponent: 'UiCommand' },
  { name: 'Context Menu', description: 'Меню по правому клику.', status: 'implemented', localComponent: 'UiContextMenu' },
  { name: 'Data Table', description: 'Таблица данных приложения.', status: 'implemented', localComponent: 'DataTable' },
  { name: 'Date Picker', description: 'Выбор даты.', status: 'alias', localComponent: 'UiCalendar' },
  { name: 'Dialog', description: 'Модальное окно.', status: 'implemented', localComponent: 'UiDialog' },
  { name: 'Direction', description: 'Направление текста.', status: 'planned' },
  { name: 'Drawer', description: 'Выезжающая панель.', status: 'alias', localComponent: 'UiSheet' },
  { name: 'Dropdown Menu', description: 'Меню действий.', status: 'implemented', localComponent: 'UiDropdownMenu' },
  { name: 'Empty', description: 'Пустое состояние.', status: 'implemented', localComponent: 'UiEmpty' },
  { name: 'Field', description: 'Label/control/error для форм.', status: 'implemented', localComponent: 'FormField' },
  { name: 'Hover Card', description: 'Карточка по наведению.', status: 'alias', localComponent: 'UiTooltip' },
  { name: 'Input', description: 'Текстовое поле.', status: 'implemented', localComponent: 'UiInput' },
  { name: 'Input Group', description: 'Input с prefix/suffix.', status: 'implemented', localComponent: 'UiInputGroup' },
  { name: 'Input OTP', description: 'Ввод одноразового кода.', status: 'implemented', localComponent: 'UiInputOtp' },
  { name: 'Item', description: 'Строка/карточка с media и actions.', status: 'implemented', localComponent: 'UiItem' },
  { name: 'Kbd', description: 'Клавиатурная подсказка.', status: 'implemented', localComponent: 'UiKbd' },
  { name: 'Label', description: 'Подпись к полю.', status: 'alias', localComponent: 'FormField' },
  { name: 'Menubar', description: 'Горизонтальное меню команд.', status: 'implemented', localComponent: 'UiMenubar' },
  { name: 'Native Select', description: 'Нативный select в дизайн-системе.', status: 'implemented', localComponent: 'UiSelect' },
  { name: 'Navigation Menu', description: 'Навигационное меню.', status: 'implemented', localComponent: 'UiNavigationMenu' },
  { name: 'Pagination', description: 'Навигация по страницам.', status: 'implemented', localComponent: 'UiPagination' },
  { name: 'Popover', description: 'Плавающая панель.', status: 'implemented', localComponent: 'UiPopover' },
  { name: 'Progress', description: 'Индикатор прогресса.', status: 'implemented', localComponent: 'UiProgress' },
  { name: 'Radio Group', description: 'Выбор одного варианта.', status: 'implemented', localComponent: 'UiRadioGroup' },
  { name: 'Resizable', description: 'Изменяемые панели.', status: 'planned' },
  { name: 'Scroll Area', description: 'Скроллируемая область.', status: 'implemented', localComponent: 'UiScrollArea' },
  { name: 'Select', description: 'Выбор значения.', status: 'implemented', localComponent: 'UiSelect' },
  { name: 'Separator', description: 'Разделитель контента.', status: 'implemented', localComponent: 'UiSeparator' },
  { name: 'Sheet', description: 'Боковая панель.', status: 'implemented', localComponent: 'UiSheet' },
  { name: 'Sidebar', description: 'Навигационная панель приложения.', status: 'implemented', localComponent: 'AppSidebar' },
  { name: 'Skeleton', description: 'Плейсхолдер загрузки.', status: 'implemented', localComponent: 'UiSkeleton' },
  { name: 'Slider', description: 'Выбор числового значения.', status: 'implemented', localComponent: 'UiSlider' },
  { name: 'Sonner', description: 'Toast/snackbar уведомления.', status: 'implemented', localComponent: 'Snackbar' },
  { name: 'Spinner', description: 'Индикатор загрузки.', status: 'implemented', localComponent: 'UiSpinner' },
  { name: 'Switch', description: 'Переключатель.', status: 'implemented', localComponent: 'UiSwitch' },
  { name: 'Table', description: 'Базовая таблица.', status: 'implemented', localComponent: 'DataTable' },
  { name: 'Tabs', description: 'Переключаемые панели.', status: 'implemented', localComponent: 'UiTabs' },
  { name: 'Textarea', description: 'Многострочный ввод.', status: 'implemented', localComponent: 'UiTextarea' },
  { name: 'Toast', description: 'Краткие уведомления.', status: 'implemented', localComponent: 'Snackbar' },
  { name: 'Toggle', description: 'Двухсостоянийная кнопка.', status: 'implemented', localComponent: 'UiToggle' },
  { name: 'Toggle Group', description: 'Группа переключателей.', status: 'implemented', localComponent: 'UiToggleGroup' },
  { name: 'Tooltip', description: 'Подсказка по hover/focus.', status: 'implemented', localComponent: 'UiTooltip' },
  { name: 'Typography', description: 'Стили текста через Tailwind utility-классы.', status: 'implemented' }
]
